version: '3'
services:
  poet-mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
  poet-rabbit:
    image: rabbitmq:3
    ports:
      - "5671-5672:5671-5672"
  poet-ipfs:
    image: jbenet/go-ipfs:latest
    ports:
      - "8080:8080"
      - "4001:4001"
      - "5001:5001"
    volumes:
      - .ipfs-docker:/data/ipfs
  poet-node:
    build: .
    command: npm start
    ports:
      - "18080:18080"
    depends_on:
      - poet-mongo
      - poet-rabbit
      - poet-ipfs